### ISSUE TITLE
Question about all the dataset & annotation

### ISSUE THREAD

**Issue by ShirleyMaxx** [jfzhang95/BMP#1]
Hi, thanks for your great work!

1. Have you provided the supp. mat.? I couldn't find it now.
2. Could you share more details about the dataset and their mesh annotations, as MoSh is not available now, so how could you get gt mesh annotations? from SMPLify-X or others?
3. When will you release the main code?

Looking forward to your reply! Thank you in advance!

**Comment by jfzhang95** [comment]
Hi, thanks for your interest in our work.

You could refer to [this work](https://github.com/JiangWenPL/multiperson) for data preparation. Although several datasets, e.g., COCO, MPI-INF-3DHP, etc. do not have mesh annotations, we can still train our model on them using 2D/3D keypoint loss and adversarial loss following [HMR](https://akanazawa.github.io/hmr/).

Our code will be released in July. Stay tuned!
